#! /usr/bin/env python

# An hook script to make use of push options.
# The script rejects ask the contributors to redo their commit
# messages if it not ends with format e.g. Fixes#585

import sys
import subprocess
import re
ref = sys.argv[1]
old_rev = sys.argv[2]
new_rev = sys.argv[3]
cp = subprocess.run(
        ['git','rev-list',old_rev+".."+new_rev],
        check=True,
        stdout=subprocess.PIPE,
        universal_newlines=True
    )
commits = cp.stdout.strip().splitlines()
for commit in commits:
    cp = subprocess.run(
        ['git','cat-file','commit',commit],
        check=True,
        stdout=subprocess.PIPE,
        universal_newlines=True
    )
    commit_msg = cp.stdout.strip().splitlines()[5]
    if not re.match(".*\[[a-zA-Z]{5}#\d{3}\]", commit_msg):
         print("Issue identifier missing at the end of commit_msg. Please add an issue identifier, eg. [Fixes#123]")
         sys.exit(1)
